spring.application.name=intern
server.port=8081
spring.datasource.url=jdbc:clickhouse://localhost:8123/default
spring.datasource.username=user1
spring.datasource.password=password1
spring.datasource.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver
spring.data.jdbc.repositories.enabled=false
logging.level.com.clickhouse.client.http=ERROR